---
os:
  - linux
language: c

node_js:
  - "5.10.1"

env:
  - export NODE_VERSION="5.10.1"

addons:
  apt:
    packages:
      - libgc-dev
      - libgmp-dev

bef_install:
  - date

install:
  - $TRAVIS_BUILD_DIR/travis-ci/install-ats2.sh 0.3.12
  - export PATSHOME=$HOME/ATS2
  - export PATH=${PATH}:${PATSHOME}/bin

script:
  - echo 'running unit-tests...'
  - cd $TRAVIS_BUILD_DIR/srcgen
  - (cd util/TEST && make testall)
  - (cd util/TEST/Posix && make testall)
  - echo 'building...'
  - cd xats
  - make all
  - export XATSHOME=$TRAVIS_BUILD_DIR
  - echo 'running integration tests...'
  - (cd TEST && make XATSOPT=$XATSHOME/srcgen/xats/xatsopt testall)
