---
os:
  - linux
language: c

node_js:
  - "5.10.1"

env:
  - export NODE_VERSION="5.10.1"

addons:
  apt:
    packages:
      - libgc-dev
      - libgmp-dev

bef_install:
  - date
  - export XATSHOME=$TRAVIS_BUILD_DIR

install_ats2:
  - $XATSHOME/travis-ci/install-ats2.sh 0.3.12

install_aft:
  - date
  - export PATSHOME=$HOME/ATS2
  - export PATH=${PATH}:${PATSHOME}/bin

testing_ats3:
  - cd $XATSHOME/srcgen
  - echo "running unit-tests..."
  - (cd util/TEST && make testall)
  - (cd util/TEST/Posix && make testall)
  - echo "building ATS-Xanadu..."
  - (cd xats && make all)
  - echo "running integration tests..."
  - (cd xats/TEST && make XATSOPT=$XATSHOME/srcgen/xats/xatsopt testall)
