---
os:
  - linux

language: c

node_js:
  - "5.10.1"

env:
  - export NODE_VERSION="5.10.1"

addons:
  apt:
    packages:
      - libgc-dev
      - libgmp-dev

before_install:
  - date
  - export PATSHOME=$HOME/ATS2
  - export PATH=${PATH}:${PATSHOME}/bin
  - export XATSHOME=$TRAVIS_BUILD_DIR

install:
  - $XATSHOME/travis-ci/install-ats2.sh 0.3.12

after_install:
  - date

before_script:
  - date

script:
  - cd $XATSHOME/srcgen
  - echo 'running unit-tests...'
  - (cd util/TEST && make testall)
  - (cd util/TEST/Posix && make testall)
  - echo 'building ATS-Xanadu...'
  - (cd xats && make all)
  - export XATSOPT=./xats/xatsopt 
  - echo 'running integration tests...'
  - (cd xats/TEST && make testall)

after_script:
  - date
